<script setup>
import { Link, usePage } from '@inertiajs/vue3';
import { computed } from 'vue';
import PageIntro from '@/Components/PageIntro.vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';

defineOptions({ layout: SiteLayout });
const site = computed(() => usePage().props.site || {});
const principles = [['Vehicle information first', 'Photos, price, mileage, specifications, and direct questions should make it easier to decide whether a vehicle deserves your time.'], ['A human way to shop', 'You can browse on your own, call when you are ready, and take the conversation one useful step at a time.'], ['Clear next steps', 'Whether you are considering financing, your current vehicle, or a visit, we keep the next action simple.']];
</script>

<template>
    <SeoHead title="About Kohl Auto Sales" description="Learn how Kohl Auto Sales approaches pre-owned vehicle shopping." />
    <PageIntro eyebrow="About Kohl" title="A simpler way to begin the car-buying conversation." description="Kohl Auto Sales is focused on helping drivers explore pre-owned vehicles with useful information, direct communication, and a clear next step." action-label="Contact Kohl" action-href="/contact" />
    <section class="site-section"><div class="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">Our approach</p><h2 class="mt-4 heading-lg">Start with what matters to you.</h2></div><div><p class="text-xl leading-9 text-kohl-muted">A vehicle should fit your life, not a sales script. Our site is designed to help you compare real details, and our team is here when you want to take the next step.</p><p class="mt-6 leading-8 text-kohl-muted">We do not rely on inflated promises. Instead, we encourage questions about the vehicle you are considering and make it straightforward to contact us, discuss financing, or tell us about a vehicle you would like to sell or trade.</p></div></div></section>
    <section class="bg-kohl-ink text-white"><div class="site-container py-16 lg:py-24"><p class="kohl-kicker">What guides us</p><div class="mt-10 grid border-y border-white/15 md:grid-cols-3"><article v-for="(principle, index) in principles" :key="principle[0]" class="border-b border-white/15 py-7 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0"><span class="text-sm font-bold text-kohl-yellow">0{{ index + 1 }}</span><h2 class="mt-5 text-2xl font-bold">{{ principle[0] }}</h2><p class="mt-3 leading-7 text-white/65">{{ principle[1] }}</p></article></div></div></section>
    <section class="site-section bg-white"><div class="site-container grid gap-8 lg:grid-cols-2"><div class="border-t-2 border-kohl-yellow pt-6"><p class="eyebrow">Shopping inventory</p><h2 class="mt-4 text-3xl font-bold">Start online, then get in touch.</h2><p class="mt-3 leading-7 text-kohl-muted">Filter our current inventory by the details that matter. If a vehicle catches your attention, send a request or call to ask about it.</p><Link href="/inventory" class="btn-ghost mt-7">Browse inventory</Link></div><div class="border-t-2 border-kohl-yellow pt-6"><p class="eyebrow">Planning a visit</p><h2 class="mt-4 text-3xl font-bold">Questions are always a good start.</h2><p class="mt-3 leading-7 text-kohl-muted">Contact Kohl Auto Sales to ask about a vehicle, directions, or the next step before you visit.</p><a :href="`tel:${site.phone_tel}`" class="btn-ghost mt-7">Call {{ site.phone }}</a></div></div></section>
    <section class="border-y border-kohl-line bg-kohl-sky"><div class="site-container grid gap-10 py-16 lg:grid-cols-[1.2fr_.8fr] lg:py-20"><div><p class="eyebrow">Serving the conversation</p><h2 class="mt-4 heading-lg">A local point of contact<br>for your next move.</h2><p class="mt-6 max-w-2xl text-lg leading-8 text-kohl-muted">Whether you are comparing vehicles from home or preparing to visit, the useful part is the same: clear details, an open question, and a next step you understand.</p></div><div class="border-l-4 border-kohl-yellow bg-white p-7"><p class="text-[10px] font-bold uppercase tracking-[.2em] text-kohl-yellow-deep">Find Kohl Auto Sales</p><p class="mt-4 text-xl font-semibold">{{ site.address }}</p><p class="mt-3 text-sm leading-6 text-kohl-muted">{{ site.business_hours }}</p><a :href="site.maps_url" target="_blank" rel="noopener" class="btn-ghost mt-7">Open directions ↗</a></div></div></section>
    <section class="site-section"><div class="site-container"><div class="max-w-2xl"><p class="eyebrow">A practical checklist</p><h2 class="mt-4 heading-lg">When a vehicle feels right.</h2></div><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div v-for="(item, index) in ['Review the photos and details', 'Write down your questions', 'Ask about availability', 'Choose a comfortable next step']" :key="item" class="border-t-2 border-kohl-blue pt-5"><span class="text-2xl font-semibold text-kohl-yellow-deep">0{{ index + 1 }}</span><p class="mt-4 font-semibold">{{ item }}</p></div></div></div></section>
</template>
