<script setup>
import { Link, useForm, usePage } from '@inertiajs/vue3';
import { computed } from 'vue';
import PageIntro from '@/Components/PageIntro.vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';

defineOptions({ layout: SiteLayout });
const site = computed(() => usePage().props.site || {});
const form = useForm({ first_name: '', last_name: '', email: '', phone: '', subject: '', message: '' });
const submit = () => form.post('/contact', { preserveScroll: true, onSuccess: () => form.reset() });
const topics = [['Vehicle availability', 'Ask about a vehicle, photos, details, or arranging a visit.'], ['Financing question', 'Ask about sending a preliminary financing request.'], ['Sell or trade', 'Talk through your current vehicle and the next step.'], ['General question', 'Send anything else you would like to discuss.']];
const contactFaq = [['Should I call before visiting?', 'Yes. Calling ahead lets the team confirm the vehicle is still available and help you plan your visit.'], ['What should I include in a message?', 'A stock number or vehicle name, your question, and the best way to reach you are useful starting points.'], ['Can I ask about directions?', 'Use the Directions link to open the provided Google Maps place, or call the dealership if you need help.']];
</script>

<template>
    <SeoHead title="Contact & directions" description="Contact Kohl Auto Sales about inventory, financing, or selling or trading your vehicle." />
    <PageIntro eyebrow="Contact Kohl" title="A good next step starts with a question." description="Call, send a message, or use Google Maps for directions. We will help you find the right next step." />
    <section class="site-section"><div class="site-container grid gap-12 xl:grid-cols-[minmax(0,1fr)_520px]"><div><div class="grid border-t border-kohl-line sm:grid-cols-2"><a :href="`tel:${site.phone_tel}`" class="border-b border-kohl-line py-7 pr-6 transition hover:text-kohl-yellow-deep"><p class="eyebrow">Call</p><p class="mt-3 text-xl font-bold">{{ site.phone }}</p></a><a :href="site.maps_url" target="_blank" rel="noopener" class="border-b border-kohl-line py-7 sm:pl-6 transition hover:text-kohl-yellow-deep"><p class="eyebrow">Directions</p><p class="mt-3 text-xl font-bold">Open in Google Maps ↗</p></a><div class="border-b border-kohl-line py-7 pr-6"><p class="eyebrow">Hours</p><p class="mt-3 font-bold leading-6">{{ site.business_hours }}</p></div><a v-if="site.email" :href="`mailto:${site.email}`" class="border-b border-kohl-line py-7 break-all sm:pl-6 transition hover:text-kohl-yellow-deep"><p class="eyebrow">Email</p><p class="mt-3 font-bold">{{ site.email }}</p></a></div><div class="mt-12"><p class="eyebrow">What can we help with?</p><div class="mt-5 grid gap-3 sm:grid-cols-2"><button v-for="topic in topics" :key="topic[0]" type="button" class="border border-kohl-line bg-white p-5 text-left transition hover:border-kohl-ink" @click="form.subject = topic[0]; document.getElementById('contact-form')?.scrollIntoView({ behavior: 'smooth', block: 'start' })"><h2 class="font-bold">{{ topic[0] }}</h2><p class="mt-2 text-sm leading-6 text-kohl-muted">{{ topic[1] }}</p></button></div></div><div class="mt-12 border-l-4 border-kohl-ink bg-kohl-sky p-6"><h2 class="text-xl font-bold">Planning a visit?</h2><p class="mt-3 leading-7 text-kohl-muted">Call ahead to confirm a vehicle is available before making the trip.</p><Link href="/inventory" class="btn-ghost mt-6">See available vehicles</Link></div></div>
        <form id="contact-form" class="dealer-panel border-t-4 border-kohl-ink p-6 sm:p-8" @submit.prevent="submit"><p class="eyebrow">Send a message</p><h2 class="mt-4 text-3xl font-bold">Tell us what you need.</h2><div class="mt-7 grid gap-4 sm:grid-cols-2"><label><span class="form-label">First name *</span><input v-model="form.first_name" required autocomplete="given-name" class="form-input-dark"><p v-if="form.errors.first_name" class="form-error">{{ form.errors.first_name }}</p></label><label><span class="form-label">Last name</span><input v-model="form.last_name" autocomplete="family-name" class="form-input-dark"></label><label><span class="form-label">Phone *</span><input v-model="form.phone" required type="tel" autocomplete="tel" class="form-input-dark"><p v-if="form.errors.phone" class="form-error">{{ form.errors.phone }}</p></label><label><span class="form-label">Email</span><input v-model="form.email" type="email" autocomplete="email" class="form-input-dark"><p v-if="form.errors.email" class="form-error">{{ form.errors.email }}</p></label></div><label class="mt-4 block"><span class="form-label">Topic</span><select v-model="form.subject" class="form-select-dark"><option value="">Select a topic</option><option v-for="topic in topics" :key="topic[0]" :value="topic[0]">{{ topic[0] }}</option></select></label><label class="mt-4 block"><span class="form-label">Message</span><textarea v-model="form.message" rows="6" class="form-input-dark"></textarea><p v-if="form.errors.message" class="form-error">{{ form.errors.message }}</p></label><button class="btn-primary mt-6 w-full" :disabled="form.processing">{{ form.processing ? 'Sending message…' : 'Send message' }}</button></form></div></section>
    <section class="site-section border-t border-kohl-line bg-kohl-sky"><div class="site-container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p class="eyebrow">Contact questions</p><h2 class="mt-4 heading-lg">Make the visit easier.</h2><p class="mt-5 leading-7 text-kohl-muted">A little planning helps the team give you a useful answer.</p></div><div class="border-t border-kohl-line"><details v-for="faq in contactFaq" :key="faq[0]" class="border-b border-kohl-line py-5"><summary class="cursor-pointer list-none text-lg font-semibold">{{ faq[0] }}</summary><p class="mt-3 max-w-2xl leading-7 text-kohl-muted">{{ faq[1] }}</p></details></div></div></section>
</template>
