<script setup>
import { Link, useForm } from '@inertiajs/vue3';
import Icon from '@/Components/Icon.vue';
import PageIntro from '@/Components/PageIntro.vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';

defineOptions({ layout: SiteLayout });
const form = useForm({ first_name: '', last_name: '', email: '', phone: '', vehicle_interest: '', amount: '', down_payment: '', term_months: '', credit_score_range: '', message: '' });
const submit = () => form.post('/finance', { preserveScroll: true, onSuccess: () => form.reset() });
const steps = [['01', 'Tell us what you’re considering', 'Add a vehicle or describe the kind of vehicle you want.'], ['02', 'Share a few planning details', 'A target amount, down payment, and term help frame the conversation.'], ['03', 'Talk through the next step', 'Our team will contact you about the request and information that may be needed.']];
const financeFaq = [['What information may be useful?', 'A vehicle of interest, a target amount, down payment, preferred term, and the best way to reach you can help start the conversation.'], ['Is this a credit application?', 'No. This form is a preliminary request for information. Any credit process or lender review will be explained separately.'], ['Do I need to choose a vehicle first?', 'No. You can describe the kind of car, SUV, or truck you are considering and update the conversation later.']];
</script>

<template>
    <SeoHead title="Financing" description="Send Kohl Auto Sales a preliminary financing request and discuss the next step with our team." />
    <PageIntro eyebrow="Financing" title="Start with a conversation, not a promise." description="Share a few planning details and our team can follow up about the vehicle and available next steps." action-label="Browse inventory" action-href="/inventory" background="1" />
    <section class="site-section"><div class="site-container grid gap-12 xl:grid-cols-[minmax(0,1fr)_510px]"><div><p class="eyebrow">How it works</p><h2 class="mt-4 heading-lg">A clear path forward.</h2><div class="mt-10 border-t border-kohl-line"><article v-for="step in steps" :key="step[0]" class="grid gap-4 border-b border-kohl-line py-7 sm:grid-cols-[70px_1fr]"><span class="text-xl font-bold text-kohl-yellow">{{ step[0] }}</span><div><h3 class="text-xl font-bold">{{ step[1] }}</h3><p class="mt-2 max-w-xl leading-7 text-kohl-muted">{{ step[2] }}</p></div></article></div><div class="mt-12 border-l-4 border-kohl-yellow bg-kohl-sky p-6"><h3 class="font-bold">A note about financing</h3><p class="mt-3 leading-7 text-kohl-muted">Submitting this form is a request for information, not a credit decision or an offer of financing. Any terms depend on the vehicle, lender review, documentation, and other applicable details.</p></div></div>
        <form class="dealer-panel border-t-4 border-kohl-ink p-6 sm:p-8" @submit.prevent="submit"><p class="eyebrow">Preliminary request</p><h2 class="mt-4 text-3xl font-bold">Tell us what you’re planning.</h2><p class="mt-3 leading-7 text-kohl-muted">Fields marked with * are required.</p><div class="mt-7 grid gap-4 sm:grid-cols-2"><label><span class="form-label">First name *</span><input v-model="form.first_name" required autocomplete="given-name" class="form-input-dark"><p v-if="form.errors.first_name" class="form-error">{{ form.errors.first_name }}</p></label><label><span class="form-label">Last name</span><input v-model="form.last_name" autocomplete="family-name" class="form-input-dark"></label><label><span class="form-label">Phone *</span><input v-model="form.phone" required type="tel" autocomplete="tel" class="form-input-dark"><p v-if="form.errors.phone" class="form-error">{{ form.errors.phone }}</p></label><label><span class="form-label">Email</span><input v-model="form.email" type="email" autocomplete="email" class="form-input-dark"><p v-if="form.errors.email" class="form-error">{{ form.errors.email }}</p></label></div><label class="mt-4 block"><span class="form-label">Vehicle of interest</span><input v-model="form.vehicle_interest" placeholder="Year, make, model — if known" class="form-input-dark"><p v-if="form.errors.vehicle_interest" class="form-error">{{ form.errors.vehicle_interest }}</p></label><div class="mt-4 grid gap-4 sm:grid-cols-3"><label><span class="form-label">Target amount</span><input v-model="form.amount" type="number" min="0" inputmode="decimal" class="form-input-dark"></label><label><span class="form-label">Down payment</span><input v-model="form.down_payment" type="number" min="0" inputmode="decimal" class="form-input-dark"></label><label><span class="form-label">Preferred term</span><select v-model="form.term_months" class="form-select-dark"><option value="">Select</option><option value="36">36 months</option><option value="48">48 months</option><option value="60">60 months</option><option value="72">72 months</option></select></label></div><label class="mt-4 block"><span class="form-label">Additional context</span><textarea v-model="form.message" rows="4" placeholder="Anything you would like us to know?" class="form-input-dark"></textarea><p v-if="form.errors.message" class="form-error">{{ form.errors.message }}</p></label><button class="btn-primary mt-6 w-full" :disabled="form.processing">{{ form.processing ? 'Sending request…' : 'Send financing request' }} <Icon name="send" /></button><p class="form-help">By submitting, you ask Kohl Auto Sales to contact you about this request.</p></form></div></section>
    <section class="border-t border-kohl-line bg-kohl-sky"><div class="site-container grid gap-8 py-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p class="eyebrow">Still browsing?</p><h2 class="mt-4 text-3xl font-bold">Start with the vehicles on our lot.</h2></div><Link href="/inventory" class="btn-secondary justify-self-start lg:justify-self-end">View inventory <Icon name="arrow-right" /></Link></div></section>
    <section class="site-section bg-white"><div class="site-container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p class="eyebrow">Prepare for the conversation</p><h2 class="mt-4 heading-lg">A little context<br>goes a long way.</h2><p class="mt-5 leading-7 text-kohl-muted">You do not need every answer before you reach out. Share what you know and ask what you need.</p></div><div class="grid gap-4 sm:grid-cols-2"><div class="border-l-4 border-kohl-yellow bg-kohl-sky p-6"><h3 class="text-xl font-semibold">Vehicle direction</h3><p class="mt-3 text-sm leading-6 text-kohl-muted">A specific vehicle or a useful description of the type you are looking for.</p></div><div class="border-l-4 border-kohl-yellow bg-kohl-sky p-6"><h3 class="text-xl font-semibold">Planning details</h3><p class="mt-3 text-sm leading-6 text-kohl-muted">A target amount, down payment, and preferred term if you have them.</p></div><div class="border-l-4 border-kohl-yellow bg-kohl-sky p-6"><h3 class="text-xl font-semibold">Contact details</h3><p class="mt-3 text-sm leading-6 text-kohl-muted">A phone number is required so our team can follow up with you.</p></div><div class="border-l-4 border-kohl-yellow bg-kohl-sky p-6"><h3 class="text-xl font-semibold">Your questions</h3><p class="mt-3 text-sm leading-6 text-kohl-muted">Use the message field to tell us what you would like to understand.</p></div></div></div></section>
    <section class="site-section border-y border-kohl-line bg-kohl-sky"><div class="site-container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p class="eyebrow">Financing questions</p><h2 class="mt-4 heading-lg">Keep the details clear.</h2></div><div class="border-t border-kohl-line"><details v-for="faq in financeFaq" :key="faq[0]" class="border-b border-kohl-line py-5"><summary class="cursor-pointer list-none text-lg font-semibold">{{ faq[0] }}</summary><p class="mt-3 max-w-2xl leading-7 text-kohl-muted">{{ faq[1] }}</p></details></div></div></section>
</template>
