<script setup>
import { Link, usePage } from '@inertiajs/vue3';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import Icon from '@/Components/Icon.vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';
import VehicleCard from '@/Components/VehicleCard.vue';

defineOptions({ layout: SiteLayout });
const props = defineProps({ featuredVehicles: { type: Array, default: () => [] }, reviews: { type: Array, default: () => [] } });
const site = computed(() => usePage().props.site || {});
const slide = ref(0);
const offers = computed(() => {
    const vehicles = props.featuredVehicles;
    return [
        { label: 'Kohl Auto Sales', title: 'A more considered way to find your next vehicle.', text: 'Explore a focused selection of pre-owned vehicles and get straightforward help from the first question onward.', cta: 'Browse inventory', href: '/inventory', image: vehicles[0]?.image_large || '/images/img-1.webp' },
        { label: 'Fresh on the lot', title: 'See what is available right now.', text: 'Browse current vehicles with clear photos, specifications, mileage, and price.', cta: 'View latest vehicles', href: '/inventory', image: vehicles[1]?.image_large || '/images/img-2.webp' },
        { label: 'Sell or trade', title: 'Your current vehicle belongs in the plan.', text: 'Start the conversation by sharing a few details about the vehicle you already own.', cta: 'Tell us about your vehicle', href: '/trade-in', image: vehicles[2]?.image_large || '/images/img-3.webp' },
        { label: 'Financing', title: 'Plan the next step with clarity.', text: 'Send a preliminary request and discuss the details with our team.', cta: 'Explore financing', href: '/finance', image: vehicles[3]?.image_large || '/images/img-4.webp' },
    ];
});
const activeOffer = computed(() => offers.value[slide.value]);
const categories = [{ label: 'Cars', href: '/inventory?body_type=sedan', note: 'Everyday driving' }, { label: 'SUVs', href: '/inventory?body_type=suv', note: 'Room for what matters' }, { label: 'Trucks', href: '/inventory?body_type=truck', note: 'Ready for the workday' }];
const process = [['01', 'Browse with context', 'Start with the inventory and use filters to narrow the vehicles that fit your needs.'], ['02', 'Ask the useful questions', 'Call or send an inquiry when you want to know more about a particular vehicle.'], ['03', 'Make the next move', 'Talk through a visit, financing request, or your current vehicle when you are ready.']];
const faqs = [
    ['Can I ask about a vehicle before visiting?', 'Yes. Use the inquiry form on a vehicle page or contact Kohl Auto Sales with the stock number and your questions.'],
    ['What if I do not see the vehicle I need?', 'Contact us with the make, model, body style, budget, and any must-have details. We can discuss what to look for next.'],
    ['Can I submit financing information before choosing a vehicle?', 'Yes. The financing form is a preliminary request for information and does not promise approval or a specific term.'],
    ['Can I sell or trade my current vehicle?', 'Yes. Send the year, make, model, mileage, condition, and contact details through the Sell or trade form.'],
];
const faqOpen = ref(0);
let timer;
onMounted(() => { timer = window.setInterval(() => { slide.value = (slide.value + 1) % offers.value.length; }, 7000); });
onBeforeUnmount(() => clearInterval(timer));
const schema = computed(() => ({ '@context': 'https://schema.org', '@type': 'AutoDealer', name: site.value.name, telephone: site.value.phone_tel, url: typeof window === 'undefined' ? undefined : window.location.origin }));
</script>

<template>
    <SeoHead :title="site.name" description="Explore quality pre-owned vehicles at Kohl Auto Sales." :schema="schema" />
    <section class="kohl-hero"><div class="kohl-hero-image" :style="{ backgroundImage: `url(${activeOffer.image})` }"></div><div class="kohl-hero-shade"></div><div class="site-container relative z-10 flex min-h-[650px] items-end py-16 lg:min-h-[720px] lg:py-24"><div class="max-w-2xl text-white"><p class="kohl-kicker">{{ activeOffer.label }}</p><h1 class="mt-5 text-5xl font-bold leading-[.9] tracking-[-.065em] sm:text-7xl">{{ activeOffer.title }}</h1><p class="mt-6 max-w-xl text-lg leading-8 text-white/80">{{ activeOffer.text }}</p><Link :href="activeOffer.href" class="btn-primary mt-8">{{ activeOffer.cta }} <Icon name="arrow-right" /></Link></div><div class="absolute bottom-8 right-5 flex gap-2 sm:right-8 lg:right-12"><button v-for="(_, index) in offers" :key="index" class="h-2 transition-all" :class="index === slide ? 'w-12 bg-kohl-yellow' : 'w-5 bg-white/40'" :aria-label="`Show offer ${index + 1}`" @click="slide = index"></button></div></div></section>
    <section class="bg-kohl-ink text-white"><div class="site-container grid sm:grid-cols-3"><Link v-for="category in categories" :key="category.label" :href="category.href" class="group flex items-center justify-between border-b border-white/15 py-6 sm:border-b-0 sm:border-r sm:px-7 sm:first:pl-0 sm:last:border-r-0"><span><span class="block text-xl font-bold">{{ category.label }}</span><span class="mt-1 block text-xs text-white/55">{{ category.note }}</span></span><Icon name="chevron-right" class="text-kohl-yellow transition group-hover:translate-x-1" /></Link></div></section>
    <section class="border-b border-kohl-line bg-kohl-blue text-white"><div class="site-container grid gap-6 py-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="kohl-kicker">Start with a question</p><h2 class="mt-3 text-3xl font-bold">Know what you need?</h2></div><div class="flex flex-wrap items-center gap-3 lg:justify-end"><Link href="/inventory" class="btn-primary">Search the inventory <Icon name="arrow-right" /></Link><Link href="/contact" class="btn-secondary border-white text-white hover:bg-white hover:text-kohl-ink">Tell us what you need</Link></div></div></section>
    <section class="site-section"><div class="site-container"><div class="section-header"><div><p class="eyebrow">On the lot</p><h2 class="mt-4 heading-lg">Vehicles worth a closer look.</h2></div><Link href="/inventory" class="btn-secondary">All inventory <Icon name="arrow-right" /></Link></div><div v-if="featuredVehicles.length" class="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><VehicleCard v-for="vehicle in featuredVehicles.slice(0, 6)" :key="vehicle.id" :vehicle="vehicle" /></div><div v-else class="border-l-4 border-kohl-yellow bg-white p-8"><h2 class="text-2xl font-bold">Inventory is being updated.</h2><p class="mt-3 text-kohl-muted">Call Kohl Auto Sales for current availability.</p><a :href="`tel:${site.phone_tel}`" class="btn-primary mt-6"><Icon name="phone" />Call {{ site.phone }}</a></div></div></section>
    <section class="bg-kohl-sky"><div class="site-container grid lg:grid-cols-[.8fr_1.2fr]"><div class="py-16 lg:py-24"><p class="eyebrow">Why Kohl</p><h2 class="mt-4 heading-lg">No big claims.<br>Just a better conversation.</h2></div><div class="py-16 lg:py-24 lg:pl-20"><p class="max-w-2xl text-lg leading-8 text-kohl-muted">We believe vehicle shopping works best when the information is clear and the next step is easy to understand. Browse at your pace, contact us when you are ready, and let the conversation guide the decision.</p><Link href="/about" class="btn-ghost mt-8">How we approach car shopping</Link></div></div></section>
    <section class="site-section bg-white"><div class="site-container"><div class="max-w-2xl"><p class="eyebrow">The process</p><h2 class="mt-4 heading-lg">A few straightforward steps.</h2></div><div class="mt-12 grid border-y border-kohl-line md:grid-cols-3"><article v-for="step in process" :key="step[0]" class="border-b border-kohl-line py-7 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0"><span class="text-sm font-bold text-kohl-yellow">{{ step[0] }}</span><h3 class="mt-5 text-2xl font-bold">{{ step[1] }}</h3><p class="mt-3 leading-7 text-kohl-muted">{{ step[2] }}</p></article></div></div></section>
    <section class="site-section bg-kohl-blue text-white"><div class="site-container grid gap-10 lg:grid-cols-2 lg:items-center"><div><p class="kohl-kicker">Your current vehicle</p><h2 class="mt-4 text-4xl font-bold leading-[.95] tracking-[-.055em] sm:text-6xl">Selling or trading?<br>Start here.</h2></div><div><p class="max-w-xl text-lg leading-8 text-white/70">Share the details about your current vehicle. It is a useful starting point whether you are replacing it or simply considering your options.</p><Link href="/trade-in" class="btn-primary mt-8">Sell or trade a vehicle <Icon name="arrow-right" /></Link></div></div></section>
    <section class="site-section"><div class="site-container grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><p class="eyebrow">Financing</p><h2 class="mt-4 heading-lg">Plan first.<br>Then move forward.</h2><p class="mt-6 max-w-xl text-lg leading-8 text-kohl-muted">If financing is part of your purchase, send a preliminary request before or after you find a vehicle. We will contact you to discuss the next step.</p><Link href="/finance" class="btn-secondary mt-8">Explore financing <Icon name="arrow-right" /></Link></div><div class="border-l-4 border-kohl-yellow bg-white p-7 sm:p-10"><p class="eyebrow">Ready to talk?</p><a :href="`tel:${site.phone_tel}`" class="mt-5 flex items-center gap-2 text-3xl font-bold tracking-[-.04em]"><Icon name="phone" />{{ site.phone }}</a><p class="mt-3 leading-7 text-kohl-muted">Have a question about inventory, a vehicle, or the next step? We would be glad to hear from you.</p><Link href="/contact" class="btn-ghost mt-8">Contact & directions <Icon name="arrow-right" /></Link></div></div></section>
    <section class="site-section border-y border-kohl-line bg-kohl-sky"><div class="site-container grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p class="eyebrow">Questions, answered</p><h2 class="mt-4 heading-lg">Useful before<br>you call.</h2><p class="mt-5 max-w-sm leading-7 text-kohl-muted">A few practical answers to help you decide what to do next.</p></div><div class="border-t border-kohl-line"><article v-for="(faq, index) in faqs" :key="faq[0]" class="border-b border-kohl-line"><button class="flex w-full items-center justify-between gap-6 py-5 text-left font-semibold" :aria-expanded="faqOpen === index" @click="faqOpen = faqOpen === index ? -1 : index"><span>{{ faq[0] }}</span><span class="text-2xl font-normal text-kohl-yellow-deep">{{ faqOpen === index ? '−' : '+' }}</span></button><p v-if="faqOpen === index" class="max-w-2xl pb-5 leading-7 text-kohl-muted">{{ faq[1] }}</p></article></div></div></section>
    <section class="bg-kohl-yellow"><div class="site-container grid gap-8 py-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p class="text-[10px] font-bold uppercase tracking-[.22em] text-kohl-ink/70">The next step is yours</p><h2 class="mt-3 text-4xl font-bold tracking-[-.05em] text-kohl-ink">Ready to look closer?</h2></div><div class="flex flex-wrap gap-3"><Link href="/inventory" class="btn-secondary">Browse vehicles <Icon name="arrow-right" /></Link><a :href="`tel:${site.phone_tel}`" class="btn-secondary"><Icon name="phone" />Call {{ site.phone }}</a></div></div></section>
    <section v-if="reviews.length" class="site-section border-t border-kohl-line bg-kohl-sky"><div class="site-container"><p class="eyebrow">From Google</p><h2 class="mt-4 heading-lg">Recent customer feedback.</h2><div class="mt-10 grid gap-5 md:grid-cols-3"><article v-for="review in reviews.slice(0, 3)" :key="review.id" class="bg-white p-7"><p class="text-sm tracking-[.2em] text-kohl-yellow">★★★★★</p><p class="mt-5 leading-7 text-kohl-muted">“{{ review.text }}”</p><p class="mt-7 text-xs font-bold uppercase tracking-[.15em]">{{ review.author_name }}</p></article></div></div></section>
</template>
