<script setup>
import { useForm } from '@inertiajs/vue3';
import Icon from '@/Components/Icon.vue';
import PageIntro from '@/Components/PageIntro.vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';

defineOptions({ layout: SiteLayout });
const form = useForm({ first_name: '', last_name: '', email: '', phone: '', make: '', model: '', year: '', mileage: '', condition: '', vin: '', message: '' });
const submit = () => form.post('/trade-in', { preserveScroll: true, onSuccess: () => form.reset() });
const steps = [['1', 'Vehicle basics', 'Year, make, model, mileage, and VIN help us understand what you have.'], ['2', 'Condition', 'Share anything useful about the vehicle’s current condition.'], ['3', 'Your contact details', 'We will follow up to discuss the information and an appropriate next step.']];
const tradeFaq = [['Is this a final appraisal?', 'No. An online request is only a starting point. A final value depends on review of the vehicle and the information provided.'], ['What if I still owe money on the vehicle?', 'Mention the existing loan in the notes. The team can tell you what payoff information may be needed.'], ['Can I submit without buying another vehicle?', 'Yes. You can share your vehicle details even if you are only exploring your options.']];
</script>

<template>
    <SeoHead title="Sell or trade" description="Tell Kohl Auto Sales about your current vehicle to begin a sell or trade conversation." />
    <PageIntro eyebrow="Sell or trade" title="Bring your current vehicle into the conversation." description="Send the basics about your car, SUV, or truck. We will review the information and contact you about the next step." action-label="Browse inventory" action-href="/inventory" background="3" />
    <section class="site-section bg-white"><div class="site-container grid gap-12 xl:grid-cols-[minmax(0,1fr)_550px]"><div><p class="eyebrow">What happens next</p><h2 class="mt-4 heading-lg">A thoughtful review starts with the details.</h2><div class="mt-10 grid gap-5"><article v-for="step in steps" :key="step[0]" class="grid grid-cols-[48px_1fr] gap-5 border-t border-kohl-line py-6"><span class="grid h-10 w-10 place-items-center bg-kohl-ink text-sm font-bold text-white">{{ step[0] }}</span><div><h3 class="text-xl font-bold">{{ step[1] }}</h3><p class="mt-2 max-w-xl leading-7 text-kohl-muted">{{ step[2] }}</p></div></article></div><p class="mt-8 max-w-xl text-sm leading-6 text-kohl-muted">An online submission is not a final offer. Any value depends on the vehicle’s inspection, condition, history, title, market conditions, and final agreement.</p></div>
        <form class="dealer-panel border-t-4 border-kohl-yellow p-6 sm:p-8" @submit.prevent="submit"><p class="eyebrow">Vehicle details</p><h2 class="mt-4 text-3xl font-bold">Tell us about your vehicle.</h2><div class="mt-7 grid gap-4 sm:grid-cols-2"><label><span class="form-label">Year *</span><input v-model="form.year" required type="number" min="1900" :max="new Date().getFullYear() + 1" class="form-input-dark"><p v-if="form.errors.year" class="form-error">{{ form.errors.year }}</p></label><label><span class="form-label">Mileage *</span><input v-model="form.mileage" required type="number" min="0" class="form-input-dark"><p v-if="form.errors.mileage" class="form-error">{{ form.errors.mileage }}</p></label><label><span class="form-label">Make *</span><input v-model="form.make" required class="form-input-dark"><p v-if="form.errors.make" class="form-error">{{ form.errors.make }}</p></label><label><span class="form-label">Model *</span><input v-model="form.model" required class="form-input-dark"><p v-if="form.errors.model" class="form-error">{{ form.errors.model }}</p></label></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><label><span class="form-label">Condition</span><select v-model="form.condition" class="form-select-dark"><option value="">Select if known</option><option>Excellent</option><option>Good</option><option>Fair</option><option>Needs attention</option></select></label><label><span class="form-label">VIN</span><input v-model="form.vin" maxlength="32" class="form-input-dark"><p v-if="form.errors.vin" class="form-error">{{ form.errors.vin }}</p></label></div><div class="mt-7 border-t border-kohl-line pt-6"><p class="form-label">Your contact details</p><div class="grid gap-4 sm:grid-cols-2"><label><span class="form-label">First name *</span><input v-model="form.first_name" required class="form-input-dark"><p v-if="form.errors.first_name" class="form-error">{{ form.errors.first_name }}</p></label><label><span class="form-label">Last name</span><input v-model="form.last_name" class="form-input-dark"></label><label><span class="form-label">Phone *</span><input v-model="form.phone" required type="tel" class="form-input-dark"><p v-if="form.errors.phone" class="form-error">{{ form.errors.phone }}</p></label><label><span class="form-label">Email</span><input v-model="form.email" type="email" class="form-input-dark"><p v-if="form.errors.email" class="form-error">{{ form.errors.email }}</p></label></div></div><label class="mt-4 block"><span class="form-label">Notes</span><textarea v-model="form.message" rows="4" class="form-input-dark"></textarea></label><button class="btn-primary mt-6 w-full" :disabled="form.processing">{{ form.processing ? 'Sending…' : 'Send vehicle details' }} <Icon name="send" /></button></form></div></section>
    <section class="site-section bg-kohl-sky"><div class="site-container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p class="eyebrow">Sell or trade questions</p><h2 class="mt-4 heading-lg">Know what the form starts.</h2><p class="mt-5 leading-7 text-kohl-muted">The online request begins a conversation. It does not promise a value or a purchase agreement.</p></div><div class="border-t border-kohl-line"><details v-for="faq in tradeFaq" :key="faq[0]" class="border-b border-kohl-line py-5"><summary class="cursor-pointer list-none text-lg font-semibold">{{ faq[0] }}</summary><p class="mt-3 max-w-2xl leading-7 text-kohl-muted">{{ faq[1] }}</p></details></div></div></section>
</template>
