<script setup>
import { Link, router } from '@inertiajs/vue3';
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue';
import PageIntro from '@/Components/PageIntro.vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';
import VehicleCard from '@/Components/VehicleCard.vue';

defineOptions({ layout: SiteLayout });
const props = defineProps({ vehicles: { type: Object, required: true }, filters: { type: Object, default: () => ({}) }, filterOptions: { type: Object, default: () => ({}) } });
const filtersOpen = ref(false);
const form = reactive({ make: props.filters.make || '', model: props.filters.model || '', year_from: props.filters.year_from || '', year_to: props.filters.year_to || '', price_min: props.filters.price_min || '', price_max: props.filters.price_max || '', mileage_min: props.filters.mileage_min || '', mileage_max: props.filters.mileage_max || '', body_type: props.filters.body_type || '', transmission: props.filters.transmission || '', drivetrain: props.filters.drivetrain || '', color: props.filters.color || '', sort: props.filters.sort || 'newest' });
const models = computed(() => !form.make ? props.filterOptions.models || [] : (props.filterOptions.models || []).filter((model) => model.make_slug === form.make));
const activeFilters = computed(() => Object.entries(form).filter(([key, value]) => key !== 'sort' && value !== '' && value !== null).map(([key, value]) => ({ key, value })));
const apply = () => { const query = {}; Object.entries(form).forEach(([key, value]) => { if (value !== '' && value !== null) query[key] = value; }); filtersOpen.value = false; router.get('/inventory', query, { preserveState: true, preserveScroll: true, replace: true }); };
const reset = () => { Object.keys(form).forEach((key) => { form[key] = key === 'sort' ? 'newest' : ''; }); router.get('/inventory', {}, { preserveState: true, preserveScroll: true, replace: true }); };
const remove = (key) => { form[key] = ''; if (key === 'make') form.model = ''; apply(); };
watch(() => form.make, (make, previous) => { if (previous && make !== previous) form.model = ''; });
const handleKeydown = (event) => { if (event.key === 'Escape' && filtersOpen.value) filtersOpen.value = false; };
watch(filtersOpen, (open) => { document.body.style.overflow = open ? 'hidden' : ''; });
onMounted(() => window.addEventListener('keydown', handleKeydown));
onBeforeUnmount(() => { window.removeEventListener('keydown', handleKeydown); document.body.style.overflow = ''; });
</script>

<template>
    <SeoHead title="Pre-owned inventory" description="Browse the current pre-owned vehicle inventory at Kohl Auto Sales." />
    <PageIntro eyebrow="Current inventory" title="Find the vehicle that fits your life." description="Browse the vehicles currently available, then narrow the list by the details that matter to you." />
    <section class="border-b border-kohl-line bg-kohl-sky"><div class="site-container grid gap-6 py-7 lg:grid-cols-[.65fr_1.35fr] lg:items-center"><div><p class="eyebrow">Quick paths</p><p class="mt-2 text-sm text-kohl-muted">Start with a body style, then refine the details.</p></div><div class="grid grid-cols-3 border-l border-kohl-line"><Link href="/inventory?body_type=sedan" class="px-4 text-sm font-semibold transition hover:text-kohl-blue sm:px-7">Cars <span class="mt-1 block text-xs font-normal text-kohl-muted">Sedans & coupes</span></Link><Link href="/inventory?body_type=suv" class="border-l border-kohl-line px-4 text-sm font-semibold transition hover:text-kohl-blue sm:px-7">SUVs <span class="mt-1 block text-xs font-normal text-kohl-muted">Room & versatility</span></Link><Link href="/inventory?body_type=truck" class="border-l border-kohl-line px-4 text-sm font-semibold transition hover:text-kohl-blue sm:px-7">Trucks <span class="mt-1 block text-xs font-normal text-kohl-muted">Capability first</span></Link></div></div></section>
    <section class="border-b border-kohl-line bg-white"><div class="site-container flex flex-wrap items-center justify-between gap-4 py-4"><div><p class="text-sm font-bold"><span class="font-bold">{{ vehicles.total }}</span> vehicle<span v-if="vehicles.total !== 1">s</span> available</p><p class="mt-1 text-xs text-kohl-muted">Use filters to compare the details that matter before contacting us.</p></div><div class="flex items-center gap-3"><button class="btn-secondary lg:hidden" :aria-expanded="filtersOpen" @click="filtersOpen = true">Filters <span v-if="activeFilters.length">{{ activeFilters.length }}</span></button><label class="flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-kohl-muted">Sort <select v-model="form.sort" class="border-b border-kohl-ink bg-transparent py-2 text-sm font-semibold normal-case outline-none" @change="apply"><option value="newest">Newest listed</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="year_desc">Year: newest</option><option value="year_asc">Year: oldest</option><option value="mileage_asc">Mileage: lowest</option><option value="mileage_desc">Mileage: highest</option></select></label></div></div></section>
    <section class="site-section"><div class="site-container grid gap-9 lg:grid-cols-[280px_minmax(0,1fr)]"><aside class="hidden lg:block"><div class="sticky top-28 border-t-2 border-kohl-ink pt-5"><div class="flex items-center justify-between"><h2 class="text-lg font-bold">Refine results</h2><button v-if="activeFilters.length" type="button" class="text-xs font-bold uppercase tracking-widest text-kohl-yellow-deep" @click="reset">Reset</button></div><form class="mt-6 grid gap-4" @submit.prevent="apply"><label><span class="form-label">Make</span><select v-model="form.make" class="form-select-dark"><option value="">Any make</option><option v-for="make in filterOptions.makes" :key="make.slug" :value="make.slug">{{ make.name }}</option></select></label><label><span class="form-label">Model</span><select v-model="form.model" class="form-select-dark"><option value="">Any model</option><option v-for="model in models" :key="model.slug" :value="model.slug">{{ model.name }}</option></select></label><label><span class="form-label">Body style</span><select v-model="form.body_type" class="form-select-dark"><option value="">Any body style</option><option v-for="(label, value) in filterOptions.bodyTypes" :key="value" :value="value">{{ label }}</option></select></label><div class="grid grid-cols-2 gap-3"><label><span class="form-label">Min price</span><input v-model="form.price_min" type="number" min="0" placeholder="$0" class="form-input-dark"></label><label><span class="form-label">Max price</span><input v-model="form.price_max" type="number" min="0" placeholder="Any" class="form-input-dark"></label></div><div class="grid grid-cols-2 gap-3"><label><span class="form-label">Year from</span><input v-model="form.year_from" type="number" min="1900" placeholder="Any" class="form-input-dark"></label><label><span class="form-label">Year to</span><input v-model="form.year_to" type="number" min="1900" placeholder="Any" class="form-input-dark"></label></div><label><span class="form-label">Transmission</span><select v-model="form.transmission" class="form-select-dark"><option value="">Any transmission</option><option v-for="(label, value) in filterOptions.transmissions" :key="value" :value="value">{{ label }}</option></select></label><label><span class="form-label">Drivetrain</span><select v-model="form.drivetrain" class="form-select-dark"><option value="">Any drivetrain</option><option v-for="(label, value) in filterOptions.drivetrains" :key="value" :value="value">{{ label }}</option></select></label><button type="submit" class="btn-primary mt-2">Apply filters</button></form></div></aside>
	        <div><div v-if="activeFilters.length" class="mb-6 flex flex-wrap items-center gap-2"><span class="text-xs font-bold uppercase tracking-[.14em] text-kohl-muted">Selected</span><button v-for="filter in activeFilters" :key="filter.key" class="border border-kohl-ink px-3 py-1.5 text-xs font-bold" @click="remove(filter.key)">{{ filter.value }} <span aria-hidden="true">×</span></button><button class="text-xs font-bold uppercase tracking-widest text-kohl-yellow-deep" @click="reset">Clear all</button></div><div v-if="vehicles.data.length" class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><VehicleCard v-for="vehicle in vehicles.data" :key="vehicle.id" :vehicle="vehicle" /></div><div v-else class="border-l-4 border-kohl-yellow bg-white p-8 sm:p-12"><p class="eyebrow">No close matches</p><h2 class="mt-4 text-3xl font-bold">Try a broader search.</h2><p class="mt-3 max-w-xl leading-7 text-kohl-muted">Remove a filter or call us to ask about the vehicles currently available.</p><div class="mt-7 flex flex-wrap gap-3"><button class="btn-primary" @click="reset">Reset filters</button><Link href="/contact" class="btn-secondary">Contact Kohl</Link></div></div><nav v-if="vehicles.links?.length > 3" class="mt-12 flex flex-wrap gap-2" aria-label="Inventory pagination"><component :is="link.url ? Link : 'span'" v-for="link in vehicles.links" :key="link.label" :href="link.url || undefined" class="grid min-h-10 min-w-10 place-items-center border px-3 text-sm font-bold" :class="link.active ? 'border-kohl-ink bg-kohl-ink text-white' : link.url ? 'border-kohl-line hover:border-kohl-ink' : 'border-kohl-sky text-kohl-muted-light'" v-html="link.label" /></nav></div></div></section>
    <Transition enter-active-class="transition" enter-from-class="opacity-0" leave-active-class="transition" leave-to-class="opacity-0"><div v-if="filtersOpen" class="fixed inset-0 z-50 bg-kohl-ink/50 lg:hidden" @click.self="filtersOpen = false"><section class="ml-auto h-full w-[min(92vw,430px)] overflow-y-auto bg-kohl-paper p-6" role="dialog" aria-modal="true" aria-label="Inventory filters"><div class="flex items-center justify-between border-b border-kohl-line pb-5"><h2 class="text-xl font-bold">Filters</h2><button class="text-2xl" aria-label="Close filters" @click="filtersOpen = false">×</button></div><form class="mt-6 grid gap-4" @submit.prevent="apply"><label><span class="form-label">Make</span><select v-model="form.make" class="form-select-dark"><option value="">Any make</option><option v-for="make in filterOptions.makes" :key="make.slug" :value="make.slug">{{ make.name }}</option></select></label><label><span class="form-label">Model</span><select v-model="form.model" class="form-select-dark"><option value="">Any model</option><option v-for="model in models" :key="model.slug" :value="model.slug">{{ model.name }}</option></select></label><label><span class="form-label">Body style</span><select v-model="form.body_type" class="form-select-dark"><option value="">Any body style</option><option v-for="(label, value) in filterOptions.bodyTypes" :key="value" :value="value">{{ label }}</option></select></label><div class="grid grid-cols-2 gap-3"><label><span class="form-label">Min price</span><input v-model="form.price_min" type="number" min="0" class="form-input-dark"></label><label><span class="form-label">Max price</span><input v-model="form.price_max" type="number" min="0" class="form-input-dark"></label></div><label><span class="form-label">Transmission</span><select v-model="form.transmission" class="form-select-dark"><option value="">Any transmission</option><option v-for="(label, value) in filterOptions.transmissions" :key="value" :value="value">{{ label }}</option></select></label><label><span class="form-label">Drivetrain</span><select v-model="form.drivetrain" class="form-select-dark"><option value="">Any drivetrain</option><option v-for="(label, value) in filterOptions.drivetrains" :key="value" :value="value">{{ label }}</option></select></label><div class="mt-3 flex gap-3"><button class="btn-primary flex-1" type="submit">Show results</button><button class="btn-secondary" type="button" @click="reset">Reset</button></div></form></section></div></Transition>
</template>
