<script setup>
import { Link, useForm, usePage } from '@inertiajs/vue3';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import SeoHead from '@/Components/SeoHead.vue';
import SiteLayout from '@/Layouts/SiteLayout.vue';
import VehicleCard from '@/Components/VehicleCard.vue';

defineOptions({ layout: SiteLayout });
const props = defineProps({ vehicle: { type: Object, required: true }, relatedVehicles: { type: Array, default: () => [] } });
const site = computed(() => usePage().props.site || {});
const activeIndex = ref(0);
const lightboxOpen = ref(false);
const inquiryOpen = ref(false);
const gallery = computed(() => {
    const images = props.vehicle.main_image ? [{ url: props.vehicle.main_image, alt: props.vehicle.name }] : [];
    (props.vehicle.images || []).forEach((image) => { if (image.url && !images.some((item) => item.url === image.url)) images.push({ url: image.url, alt: image.alt || props.vehicle.name }); });
    return images;
});
const activeImage = computed(() => gallery.value[activeIndex.value] || null);
const specs = computed(() => [['Mileage', props.vehicle.mileage], ['Transmission', props.vehicle.transmission], ['Drivetrain', props.vehicle.drivetrain], ['Engine', props.vehicle.engine], ['Exterior', props.vehicle.exterior_color], ['VIN', props.vehicle.vin]]);
const vehicleFaq = [
    ['How do I ask about this vehicle?', 'Use Request information to send your contact details and questions, or call the dealership directly.'],
    ['Can I discuss financing for this vehicle?', 'Yes. Use the financing page to send a preliminary request, then mention this vehicle in the vehicle-interest field.'],
    ['Can I bring a trade-in?', 'Yes. The Sell or trade form lets you share the details of your current vehicle before you visit.'],
];
const form = useForm({ first_name: '', last_name: '', email: '', phone: '', preferred_contact_time: '', message: '' });
const submit = () => form.post(`/inventory/${props.vehicle.slug}/inquiry`, { preserveScroll: true, onSuccess: () => form.reset() });
const next = () => { if (gallery.value.length) activeIndex.value = (activeIndex.value + 1) % gallery.value.length; };
const previous = () => { if (gallery.value.length) activeIndex.value = activeIndex.value === 0 ? gallery.value.length - 1 : activeIndex.value - 1; };
const handleKeydown = (event) => { if (!lightboxOpen.value) return; if (event.key === 'Escape') lightboxOpen.value = false; if (event.key === 'ArrowRight') next(); if (event.key === 'ArrowLeft') previous(); };
const vehicleSchema = computed(() => ({ '@context': 'https://schema.org', '@type': 'Vehicle', name: props.vehicle.name, image: gallery.value.map((image) => image.url), vehicleIdentificationNumber: props.vehicle.vin || undefined, mileageFromOdometer: props.vehicle.mileage ? { '@type': 'QuantitativeValue', value: String(props.vehicle.mileage).replace(/[^\d]/g, ''), unitCode: 'SMI' } : undefined }));
onMounted(() => window.addEventListener('keydown', handleKeydown));
onBeforeUnmount(() => window.removeEventListener('keydown', handleKeydown));
</script>

<template>
    <SeoHead :title="vehicle.seo_title || vehicle.name" :description="vehicle.seo_description || vehicle.short_description || `View details and ask about ${vehicle.name}.`" :image="vehicle.main_image" type="product" :schema="vehicleSchema" />
    <section class="border-b border-kohl-line bg-kohl-sky"><div class="site-container py-7"><nav class="flex flex-wrap gap-2 text-xs font-bold text-kohl-muted" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/inventory">Inventory</Link><span>/</span><span class="truncate">{{ vehicle.name }}</span></nav><div class="mt-8 grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p class="eyebrow">Available now</p><h1 class="mt-4 text-4xl font-bold leading-[.93] tracking-[-.06em] sm:text-6xl">{{ vehicle.name }}</h1><p v-if="vehicle.short_description" class="mt-5 max-w-2xl leading-7 text-kohl-muted">{{ vehicle.short_description }}</p></div><div class="border-l-2 border-kohl-yellow pl-5"><p class="text-[10px] font-bold uppercase tracking-[.18em] text-kohl-muted">Asking price</p><p class="mt-2 text-3xl font-bold tracking-[-.04em]">{{ vehicle.price }}</p></div></div></div></section>
    <section class="site-section"><div class="site-container grid gap-10 xl:grid-cols-[minmax(0,1.35fr)_380px]"><div><div class="relative aspect-[16/10] overflow-hidden bg-kohl-sky"><button v-if="activeImage" class="h-full w-full" aria-label="Open vehicle photo gallery" @click="lightboxOpen = true"><img :src="activeImage.url" :alt="activeImage.alt" class="h-full w-full object-cover"></button><div v-else class="grid h-full place-items-center text-xs font-bold uppercase tracking-[.2em] text-kohl-muted">Image coming soon</div><div v-if="gallery.length > 1" class="absolute bottom-4 right-4 flex gap-2"><button class="grid h-10 w-10 place-items-center bg-kohl-ink text-white" aria-label="Previous image" @click="previous">←</button><button class="grid h-10 w-10 place-items-center bg-kohl-ink text-white" aria-label="Next image" @click="next">→</button></div></div><div v-if="gallery.length > 1" class="mt-3 flex gap-3 overflow-x-auto pb-2"><button v-for="(image, index) in gallery" :key="image.url" class="h-20 w-28 shrink-0 overflow-hidden border-2" :class="index === activeIndex ? 'border-kohl-yellow' : 'border-transparent'" :aria-label="`View image ${index + 1}`" @click="activeIndex = index"><img :src="image.url" :alt="image.alt" class="h-full w-full object-cover"></button></div><div class="mt-12 border-t border-kohl-line pt-8"><h2 class="text-3xl font-bold">Vehicle details</h2><dl class="mt-7 grid border-l border-t border-kohl-line sm:grid-cols-2"><div v-for="([label, value]) in specs" :key="label" class="border-b border-r border-kohl-line p-4"><dt class="text-[10px] font-bold uppercase tracking-[.16em] text-kohl-muted">{{ label }}</dt><dd class="mt-2 font-bold">{{ value || '—' }}</dd></div></dl></div><div v-if="vehicle.description_html" class="mt-12 border-t border-kohl-line pt-8"><h2 class="text-3xl font-bold">About this vehicle</h2><div class="vehicle-description" v-html="vehicle.description_html"></div></div><div v-if="vehicle.features?.length" class="mt-12 border-t border-kohl-line pt-8"><h2 class="text-3xl font-bold">Highlights</h2><ul class="mt-6 grid gap-3 sm:grid-cols-2"><li v-for="feature in vehicle.features" :key="typeof feature === 'string' ? feature : feature.label || feature.name" class="border-l-2 border-kohl-yellow pl-3 text-sm font-semibold">{{ typeof feature === 'string' ? feature : feature.label || feature.name }}</li></ul></div></div>
        <aside class="xl:sticky xl:top-28 xl:self-start"><div class="dealer-panel border-t-4 border-kohl-ink p-6 sm:p-8"><p class="eyebrow">Interested in this vehicle?</p><h2 class="mt-4 text-3xl font-bold tracking-[-.04em]">Let’s talk.</h2><p class="mt-3 leading-7 text-kohl-muted">Ask about availability, arrange a visit, or request more information.</p><button class="btn-primary mt-7 w-full" @click="inquiryOpen = true">Request information</button><a :href="`tel:${site.phone_tel}`" class="btn-secondary mt-3 w-full">Call {{ site.phone }}</a><Link href="/finance" class="btn-ghost mt-6">Explore financing</Link><Link href="/trade-in" class="btn-ghost mt-5">Sell or trade a vehicle</Link></div><form v-if="inquiryOpen" class="dealer-panel mt-5 p-6" @submit.prevent="submit"><div class="flex items-center justify-between"><h2 class="text-xl font-bold">Request information</h2><button type="button" aria-label="Close form" @click="inquiryOpen = false">×</button></div><div class="mt-6 grid gap-4"><label><span class="form-label">First name</span><input v-model="form.first_name" required class="form-input-dark"><p v-if="form.errors.first_name" class="form-error">{{ form.errors.first_name }}</p></label><label><span class="form-label">Phone</span><input v-model="form.phone" required type="tel" class="form-input-dark"><p v-if="form.errors.phone" class="form-error">{{ form.errors.phone }}</p></label><label><span class="form-label">Email <span class="normal-case tracking-normal">(optional)</span></span><input v-model="form.email" type="email" class="form-input-dark"><p v-if="form.errors.email" class="form-error">{{ form.errors.email }}</p></label><label><span class="form-label">Message <span class="normal-case tracking-normal">(optional)</span></span><textarea v-model="form.message" rows="4" class="form-input-dark"></textarea></label><button class="btn-primary w-full" :disabled="form.processing">{{ form.processing ? 'Sending…' : 'Send request' }}</button></div></form></aside></div></section>
    <section v-if="relatedVehicles.length" class="site-section border-t border-kohl-line bg-kohl-sky"><div class="site-container"><div class="section-header"><div><p class="eyebrow">Keep looking</p><h2 class="mt-4 heading-lg">More vehicles to consider.</h2></div><Link href="/inventory" class="btn-secondary">View all</Link></div><div class="grid gap-5 md:grid-cols-3"><VehicleCard v-for="related in relatedVehicles" :key="related.id" :vehicle="related" /></div></div></section>
    <section class="border-y border-kohl-line bg-white"><div class="site-container grid gap-10 py-16 lg:grid-cols-[.7fr_1.3fr] lg:py-20"><div><p class="eyebrow">Your next step</p><h2 class="mt-4 heading-lg">A good request is specific.</h2><p class="mt-5 leading-7 text-kohl-muted">Ask about the details you care about, arrange a conversation, and let the team confirm what is current.</p></div><div class="grid gap-4 sm:grid-cols-3"><div class="border-t-2 border-kohl-yellow pt-4"><span class="text-2xl font-semibold text-kohl-blue">01</span><p class="mt-3 text-sm font-semibold">Send an inquiry</p></div><div class="border-t-2 border-kohl-yellow pt-4"><span class="text-2xl font-semibold text-kohl-blue">02</span><p class="mt-3 text-sm font-semibold">Discuss the vehicle</p></div><div class="border-t-2 border-kohl-yellow pt-4"><span class="text-2xl font-semibold text-kohl-blue">03</span><p class="mt-3 text-sm font-semibold">Choose the next step</p></div></div></div></section>
    <section class="site-section bg-kohl-sky"><div class="site-container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p class="eyebrow">Vehicle questions</p><h2 class="mt-4 heading-lg">Before you make the trip.</h2></div><div class="border-t border-kohl-line"><details v-for="faq in vehicleFaq" :key="faq[0]" class="border-b border-kohl-line py-5"><summary class="cursor-pointer list-none pr-8 text-lg font-semibold">{{ faq[0] }}</summary><p class="mt-3 max-w-2xl leading-7 text-kohl-muted">{{ faq[1] }}</p></details></div></div></section>
    <div v-if="lightboxOpen" class="fixed inset-0 z-[70] grid place-items-center bg-kohl-ink/95 p-5" role="dialog" aria-modal="true" aria-label="Vehicle photo gallery" @click.self="lightboxOpen = false"><button class="absolute right-5 top-5 text-4xl text-white" aria-label="Close gallery" @click="lightboxOpen = false">×</button><button v-if="gallery.length > 1" class="absolute left-5 text-4xl text-white" aria-label="Previous image" @click="previous">‹</button><img v-if="activeImage" :src="activeImage.url" :alt="activeImage.alt" class="max-h-[85vh] max-w-full object-contain"><button v-if="gallery.length > 1" class="absolute right-5 text-4xl text-white" aria-label="Next image" @click="next">›</button></div>
</template>
